# Generated by Django 3.2.3 on 2021-06-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_entity_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='identifier',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
