# Generated by Django 3.2.3 on 2021-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210613_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='XKX',
            field=models.BooleanField(default=False),
        ),
    ]
