# Generated by Django 3.2.3 on 2021-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_entity_xkx'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='identifier',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
